spring:
  profiles:
    active: dev

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://usre:password@localhost:19000/eureka/
      instance-id: ${spring.application.name}:${server.port}