server:
  port: 19100

eureka:
  instance:
    hostname: config
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:19000/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lidongbei/mall.git
          username:
          password:
